"""Data structures for feature-level documentation.

These sit alongside the OKF concept-page pipeline (skeleton -> enricher ->
render -> sync) but describe a coarser unit: a *feature*, i.e. a named piece
of business functionality implemented by a cluster of files/symbols, rather
than a single code concept.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, Literal

from pydantic import BaseModel, Field


@dataclass
class FileInventory:
    """One repo file, summarized for the feature-map LLM call."""

    file_id: str
    path: str
    rel_path: str
    language: str
    top_dir: str
    exports: list[str] = field(default_factory=list)
    symbols: list[str] = field(default_factory=list)
    routes: list[str] = field(default_factory=list)
    summary: str = ""
    concept_hash: str = ""


class FeatureSpec(BaseModel):
    """One entry of a feature map (LLM output, coerced)."""

    slug: str
    title: str
    description: str = ""
    kind: Literal["user-facing", "integration", "data", "infrastructure", "other"] = "other"
    member_files: list[str] = Field(default_factory=list)
    entry_points_hint: list[str] = Field(default_factory=list)
    tags: list[str] = Field(default_factory=list)


class FeatureMap(BaseModel):
    app: str
    repo: str
    generated_at: str
    model: str
    features: list[FeatureSpec] = Field(default_factory=list)


class EntryPoint(BaseModel):
    kind: str
    name: str
    file: str
    line: int | None = None


class Entity(BaseModel):
    name: str
    description: str = ""


class FeatureDoc(BaseModel):
    """Per-feature LLM output (coerced), before rendering to Markdown."""

    title: str
    description: str = ""
    overview: str = ""
    business_rules: list[str] = Field(default_factory=list)
    process_flow: list[str] = Field(default_factory=list)
    entities: list[Entity] = Field(default_factory=list)
    entry_points: list[EntryPoint] = Field(default_factory=list)
    dependencies: list[str] = Field(default_factory=list)
    edge_cases: list[str] = Field(default_factory=list)
    open_questions: list[str] = Field(default_factory=list)
    tags: list[str] = Field(default_factory=list)
    mermaid: str | None = None


class FeatureFrontmatter(BaseModel):
    type: Literal["Feature"] = "Feature"
    okf_feature_version: str = "0.1"
    title: str = Field(min_length=1, max_length=120)
    slug: str = Field(pattern=r"^[a-z0-9]+(-[a-z0-9]+)*$", max_length=60)
    description: str = Field(default="", max_length=300)
    app: str
    repo: str
    feature_id: str
    kind: str = "other"
    members_hash: str = Field(pattern=r"^[0-9a-f]{16}$")
    member_files: list[str] = Field(default_factory=list)
    member_ids: list[str] = Field(default_factory=list)
    source: Literal["llm", "human"] = "llm"
    stale: bool = False
    stale_since: str | None = None
    generated_at: str
    edited_at: str | None = None
    # The members_hash a human last reviewed against (set once, at edit time,
    # via features/store.py:save_feature_page); distinct from `members_hash`,
    # which build.py keeps advancing to the *current* code state so a later
    # build can detect drift by comparing the two.
    edited_members_hash: str | None = None
    model: str | None = None
    language: str = "en"
    tags: list[str] = Field(default_factory=list)
    needs_reembed: bool = False


@dataclass
class FeaturePage:
    fm: FeatureFrontmatter
    body: str


class DocumentFrontmatter(BaseModel):
    """Frontmatter for a human-authored, free-form Markdown ``WikiPage``.

    Unlike ``FeatureFrontmatter`` this has no members_hash/stale machinery —
    a Document is never (re)generated by the feature-mapper build, only
    created/edited/deleted directly by a person via the dashboard.
    """

    type: Literal["Document"] = "Document"
    okf_document_version: str = "0.1"
    title: str = Field(min_length=1, max_length=200)
    slug: str = Field(pattern=r"^[a-z0-9]+(-[a-z0-9]+)*$", max_length=80)
    description: str = Field(default="", max_length=300)
    app: str
    repo: str | None = None  # None => an app-level document (not scoped to one repo)
    doc_id: str
    category: Literal["note", "guide", "adr", "runbook", "spec", "other"] = "note"
    tags: list[str] = Field(default_factory=list)
    source: Literal["human"] = "human"
    created_at: str
    edited_at: str | None = None
    language: str = "en"
    word_count: int = 0
    mentions: list[str] = Field(default_factory=list)
    source_file: str | None = None
    needs_reembed: bool = False


@dataclass
class DocumentPage:
    fm: DocumentFrontmatter
    body: str


@dataclass
class ExistingFeature:
    """Feature-page state already in Neo4j, loaded before a build/sync pass.

    Carries every human-visible field (title/description/kind/tags), not just
    `content` — preserving an edit means never silently overwriting any of
    these with the mapper's fresh guess, only refreshing the bookkeeping
    fields (`members_hash`/`stale`/...) that must track the current code.
    """

    wiki_id: str
    feature_id: str
    slug: str
    source: str
    members_hash: str
    edited_members_hash: str | None
    content: str
    stale: bool
    stale_since: str | None = None
    title: str = ""
    description: str = ""
    kind: str = "other"
    tags: list[str] = field(default_factory=list)
    generated_at: str = ""
    edited_at: str | None = None


@dataclass
class ValidationIssue:
    code: str
    message: str
    line: int | None = None


@dataclass
class ValidationResult:
    ok: bool
    errors: list[ValidationIssue] = field(default_factory=list)
    warnings: list[ValidationIssue] = field(default_factory=list)


@dataclass
class FeatureBuildRequest:
    repo_path: str
    app: str
    repo_name: str
    repo_id: str
    bundle_dir: str | None
    language: str = "en"
    model_map: str = ""
    model_doc: str = ""
    concurrency: int = 4
    force: bool = False
    dry_run: bool = False
    only_slugs: list[str] | None = None


@dataclass
class FeatureBuildDeps:
    """Injected collaborators, so build_feature_docs is testable with fakes."""

    llm_client: Any | None
    graph_store: Any | None
    vector_store: Any | None
    embedder: Any | None
    tokenizer_name: str | None = None


@dataclass
class FeatureBuildResult:
    features: int = 0
    generated: int = 0
    cached: int = 0
    kept_human: int = 0
    stale: int = 0
    deleted: int = 0
    chunks: int = 0
    needs_reembed: int = 0
    warnings: list[str] = field(default_factory=list)
